"""Added Authenticatioc

Revision ID: 97a19aeda0db
Revises: 5285661ea2d6
Create Date: 2025-03-05 23:38:26.906157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a19aeda0db'
down_revision: Union[str, None] = '5285661ea2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('tasks', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('hashed_password', sa.String(length=100), nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('tasks', 'owner_id')
    op.alter_column('projects', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
